# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temp.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 852)
        # MainWindow.resize(774, 852)
        MainWindow.setWindowFlags(Qt.WindowMinimizeButtonHint | Qt.WindowCloseButtonHint)
        MainWindow.setStyleSheet("#MainWindow{border-image:url(./image_main.jpg);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.price_slider = QtWidgets.QSlider(self.centralwidget)
        self.price_slider.setGeometry(QtCore.QRect(240, 180, 301, 51))
        self.price_slider.setOrientation(QtCore.Qt.Horizontal)
        self.price_slider.setObjectName("price_slider")
        self.Maxprice = QtWidgets.QLabel(self.centralwidget)
        self.Maxprice.setGeometry(QtCore.QRect(110, 180, 121, 41))
        font = QtGui.QFont()
        font.setFamily("漢儀新蒂青松小楷")
        font.setPointSize(20)
        self.Maxprice.setFont(font)
        self.Maxprice.setObjectName("Maxprice")
        self.topic = QtWidgets.QLabel(self.centralwidget)
        self.topic.setGeometry(QtCore.QRect(200, 60, 351, 81))
        self.topic.setMaximumSize(QtCore.QSize(351, 16777215))
        font = QtGui.QFont()
        font.setFamily("漢儀新蒂青松小楷")
        font.setPointSize(48)
        self.topic.setFont(font)
        self.topic.setTextFormat(QtCore.Qt.AutoText)
        self.topic.setScaledContents(False)
        self.topic.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.topic.setWordWrap(False)
        self.topic.setOpenExternalLinks(False)
        self.topic.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.topic.setObjectName("topic")
        self.type_label = QtWidgets.QLabel(self.centralwidget)
        self.type_label.setGeometry(QtCore.QRect(80, 280, 74, 51))
        font = QtGui.QFont()
        font.setFamily("漢儀新蒂青松小楷")
        font.setPointSize(30)
        self.type_label.setFont(font)
        self.type_label.setObjectName("type_label")
        self.topping_label = QtWidgets.QLabel(self.centralwidget)
        self.topping_label.setGeometry(QtCore.QRect(255, 280, 131, 51))
        font = QtGui.QFont()
        font.setFamily("漢儀新蒂青松小楷")
        font.setPointSize(30)
        self.topping_label.setFont(font)
        self.topping_label.setObjectName("topping_label")
        self.caffeine_label = QtWidgets.QLabel(self.centralwidget)
        self.caffeine_label.setGeometry(QtCore.QRect(420, 280, 141, 51))
        font = QtGui.QFont()
        font.setFamily("漢儀新蒂青松小楷")
        font.setPointSize(30)
        self.caffeine_label.setFont(font)
        self.caffeine_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.caffeine_label.setObjectName("caffeine_label")
        self.region_label = QtWidgets.QLabel(self.centralwidget)
        self.region_label.setGeometry(QtCore.QRect(595, 280, 141, 51))
        font = QtGui.QFont()
        font.setFamily("漢儀新蒂青松小楷")
        font.setPointSize(30)
        self.region_label.setFont(font)
        self.region_label.setObjectName("region_label")
        self.type_list = QtWidgets.QComboBox(self.centralwidget)
        self.type_list.setGeometry(QtCore.QRect(80, 360, 81, 31))
        self.type_list.setObjectName("type_list")
        self.type_list.addItem("")
        self.type_list.setItemText(0, "")
        self.type_list.addItem("")
        self.type_list.addItem("")
        self.type_list.addItem("")
        self.type_list.addItem("")
        self.topping_list = QtWidgets.QComboBox(self.centralwidget)
        self.topping_list.setGeometry(QtCore.QRect(250, 360, 81, 31))
        self.topping_list.setObjectName("topping_list")
        self.topping_list.addItem("")
        self.topping_list.setItemText(0, "")
        self.topping_list.addItem("")
        self.topping_list.addItem("")
        self.topping_list.addItem("")
        self.topping_list.addItem("")
        self.topping_list.addItem("")
        self.caffeine = QtWidgets.QCheckBox(self.centralwidget)
        self.caffeine.setGeometry(QtCore.QRect(420, 360, 85, 19))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.caffeine.setFont(font)
        self.caffeine.setObjectName("caffeine")
        self.region_list = QtWidgets.QComboBox(self.centralwidget)
        self.region_list.setGeometry(QtCore.QRect(590, 360, 81, 31))
        self.region_list.setObjectName("region_list")
        self.region_list.addItem("")
        self.region_list.setItemText(0, "")
        self.region_list.addItem("")
        self.region_list.addItem("")
        self.region_list.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 400, 121, 90))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("border-image: url(./fococlipping-20220107-0114.png);")
        self.display_area = QtWidgets.QScrollArea(self.centralwidget)
        self.display_area.setGeometry(QtCore.QRect(70, 470, 621, 351))
        self.display_area.setWidgetResizable(True)
        self.display_area.setObjectName("display_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 619, 349))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.scrollArea.setWidget(self.label)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setAutoFillBackground(False)
        self.label.setGeometry(QtCore.QRect(0, 0, 621, 349))
        self.label.setObjectName("label")
        self.label.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.display_area.setWidget(self.label)
        self.price_display = QtWidgets.QLabel(self.centralwidget)
        self.price_display.setGeometry(QtCore.QRect(570, 190, 111, 41))
        font = QtGui.QFont()
        font.setFamily("漢儀新蒂青松小楷")
        font.setPointSize(15)
        self.price_display.setFont(font)
        self.price_display.setText("")
        self.price_display.setObjectName("price_display")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DBMS_final team9"))
        MainWindow.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p><p><br/></p></body></html>"))
        self.Maxprice.setText(_translate("MainWindow", "最高價格:"))
        self.topic.setText(_translate("MainWindow", "飲料查詢系統"))
        self.type_label.setText(_translate("MainWindow", "種類"))
        self.topping_label.setText(_translate("MainWindow", "配料"))
        self.caffeine_label.setText(_translate("MainWindow", "咖啡因"))
        self.region_label.setText(_translate("MainWindow", "地區"))
        self.type_list.setItemText(1, _translate("MainWindow", "單茶"))
        self.type_list.setItemText(2, _translate("MainWindow", "奶茶"))
        self.type_list.setItemText(3, _translate("MainWindow", "水果茶"))
        self.type_list.setItemText(4, _translate("MainWindow", "非茶類"))
        self.topping_list.setItemText(1, _translate("MainWindow", "水果"))
        self.topping_list.setItemText(2, _translate("MainWindow", "珍珠"))
        self.topping_list.setItemText(3, _translate("MainWindow", "椰果"))
        self.topping_list.setItemText(4, _translate("MainWindow", "布丁"))
        self.topping_list.setItemText(5, _translate("MainWindow", "燕麥"))
        self.caffeine.setText(_translate("MainWindow", "無咖啡因"))
        self.region_list.setItemText(1, _translate("MainWindow", "北"))
        self.region_list.setItemText(2, _translate("MainWindow", "中"))
        self.region_list.setItemText(3, _translate("MainWindow", "南"))
        self.pushButton.setText(_translate("MainWindow", ""))
        self.label.setText(_translate("MainWindow", "OUTPUT SHOW AT HERE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

